name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:opam-slim
    steps:
      - uses: actions/checkout@v2
      - run: make doc-ci
