name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amutake/satysfi:nightly
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update && apt-get install -y make wget
      - run: make example-ci
