name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build test files and the manual
        run: |
          docker run --rm -v "$(pwd):/satysfi" amutake/satysfi:0.0.8-opam-slim \
            sh -c "opam pin add satysfi-class-shinchoku-tairiku . && satyrographos install && ./test/build.sh && satysfi doc/manual.saty"

      - name: Check test files
        id: check
        run: |
          docker run -v "$(pwd):/satysfi" -w /satysfi alpine:3.17 \
            sh -c "apk add --no-cache diff-pdf && ./test/check.sh"

      - name: Upload the manual
        uses: actions/upload-artifact@v3
        with:
          name: manual
          path: doc/manual.pdf

      - name: Upload diff files if some tests have failed
        uses: actions/upload-artifact@v3
        if: failure() && steps.check.outcome == 'failure'
        with:
          name: diff
          path: test/*_diff.pdf
